# Travis CI checks for pajbot

language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip

python:
  - 3.4

services:
  - mysql
  - redis-server

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - pip install pip flake8 flake8-quotes --upgrade
  - flake8

install:
  - pip install -r pip-requirements.txt
  - cp ./install/config.example.ini ./config.ini

script:
  - cd tests && ./tests.py
